# Generated by Django 3.2.3 on 2021-07-18 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210128_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.IntegerField(choices=[(1, 'backup'), (2, 'restore')])),
                ('file', models.FileField(upload_to='backup')),
            ],
        ),
        migrations.AlterField(
            model_name='reservation',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserved_patients', to='app.clinic'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserved_clinics', to='app.patient'),
        ),
    ]
